Repository bmanara/IoTether, pull requests merged in 2024-07, with the labels that each got.

#167 164 fix bug regarding boss room when player restarts
  IoTether/Assets/Scripts/BossRoom Scripts/BossBattle.cs
  IoTether/Assets/Scripts/BossRoom Scripts/BossTrigger.cs
  IoTether/Assets/Scripts/Managers/GameManager.cs
  IoTether/Assets/Scripts/PlayerScripts/PlayerHealth.cs
Labels: bug

#169 Add aiming with melee weapons
  IoTether/Assets/Scripts/WeaponScripts/AimController.cs
  IoTether/Assets/Scripts/WeaponScripts/MeleeWeapon.cs
Labels: enhancement

#170 161 add speed perk
  IoTether/Assets/Prefabs/Perks/SpeedPerk Variant.prefab
  IoTether/Assets/Prefabs/Perks/SpeedPerk Variant.prefab.meta
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scripts/Managers/GameManager.cs
  IoTether/Assets/Scripts/PerkScripts/SmallSpeedPerk.asset
  IoTether/Assets/Scripts/PerkScripts/SmallSpeedPerk.asset.meta
  IoTether/Assets/Scripts/PerkScripts/SpeedPerk.cs
  IoTether/Assets/Scripts/PerkScripts/SpeedPerk.cs.meta
  IoTether/Assets/Scripts/PlayerScripts/PlayerControllers.cs
Labels: enhancement

#172 Add slight delay to RespawnPlayer
  IoTether/Assets/Scripts/Managers/GameManager.cs
Labels: bug

#173 Edit offset of BossWall
  IoTether/Assets/Prefabs/Props/Boss Room Wall (Left).prefab
  IoTether/Assets/Scenes/Level3.unity
Labels: enhancement

#174 168 add healing replenish mechanic onto the fountains
  IoTether/Assets/Prefabs/Perks/EnergyRefillPerk Variant.prefab
  IoTether/Assets/Prefabs/Perks/EnergyRefillPerk Variant.prefab.meta
  IoTether/Assets/Prefabs/Perks/HealthRefillPerk Variant.prefab
  IoTether/Assets/Prefabs/Perks/HealthRefillPerk Variant.prefab.meta
  IoTether/Assets/Prefabs/Props/Energy Fountain.prefab
  IoTether/Assets/Prefabs/Props/Energy Fountain.prefab.meta
  IoTether/Assets/Prefabs/Props/Health Fountain.prefab
  IoTether/Assets/Prefabs/Props/Health Fountain.prefab.meta
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scripts/PerkScripts/Perk Objects.meta
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/BigHealthPerk.asset
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/BigHealthPerk.asset.meta
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/EnergyRefill.asset
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/EnergyRefill.asset.meta
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/HealthRefill.asset
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/HealthRefill.asset.meta
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/SmallEnergyPerk.asset
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/SmallEnergyPerk.asset.meta
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/SmallHealthPerk.asset
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/SmallHealthPerk.asset.meta
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/SmallSpeedPerk.asset
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/SmallSpeedPerk.asset.meta
  IoTether/Assets/Scripts/StageScripts/FountainScript.cs
  IoTether/Assets/Scripts/StageScripts/FountainScript.cs.meta
Labels: enhancement

#177 176 finish remaning rooms in level 4
  IoTether/Assets/Intefaces.meta
  IoTether/Assets/Prefabs/Props/Area 2 FinalDoor .prefab
  IoTether/Assets/Prefabs/Props/Area 2 FinalDoor .prefab.meta
  IoTether/Assets/Prefabs/Props/Gate.prefab
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scenes/Level4.unity
Labels: enhancement

#179 149 create chestmechanic for new weapons
  IoTether/Assets/Prefabs/NPC.prefab
  IoTether/Assets/Prefabs/Prompt.prefab
  IoTether/Assets/Prefabs/Prompt.prefab.meta
  IoTether/Assets/Prefabs/Props/Chest.prefab
  IoTether/Assets/Prefabs/Props/Chest.prefab.meta
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scenes/Level3.unity
  IoTether/Assets/Scenes/Level4.unity
  IoTether/Assets/Scenes/TutorialScene.unity
  IoTether/Assets/Scripts/Interfaces/InteractableProp.cs
  IoTether/Assets/Scripts/Interfaces/InteractableProp.cs.meta
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/SmallSpeedPerk.asset
  IoTether/Assets/Scripts/StageScripts/ChestController.cs
  IoTether/Assets/Scripts/StageScripts/ChestController.cs.meta
  IoTether/Assets/Scripts/StageScripts/FountainScript.cs
Labels: enhancement

#183 Change Sniper Drop to a Chest in Level 2
  IoTether/Assets/Prefabs/NPC.prefab
  IoTether/Assets/Scenes/Level1.unity
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scenes/Level3.unity
Labels: enhancement

#187 182 create level 5
  IoTether/Assets/Prefabs/NPC.prefab
  IoTether/Assets/Prefabs/Props/Area 2 FinalDoor .prefab
  IoTether/Assets/Prefabs/Props/Chest.prefab
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scenes/Level3.unity
  IoTether/Assets/Scenes/Level4.unity
  IoTether/Assets/Scenes/Level5.unity
  IoTether/Assets/Scenes/Level5.unity.meta
  IoTether/Assets/Scenes/TutorialScene.unity
  IoTether/Assets/Scripts/Managers/ScenesManager.cs
  IoTether/Assets/Scripts/WeaponScripts/PumpShotgunController.cs
  IoTether/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#192 Add composite colliders to levels
  IoTether/Assets/Scenes/Level1.unity
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scenes/Level3.unity
  IoTether/Assets/Scenes/Level4.unity
  IoTether/Assets/Scenes/Level5.unity
  IoTether/Assets/Scenes/TutorialScene.unity
Labels: bug

#198 178 implement new enemies into level 4
  IoTether/Assets/Prefabs/Banana.prefab
  IoTether/Assets/Scenes/Level4.unity
  IoTether/Assets/Scenes/Level5.unity
  IoTether/Assets/Scripts/StageScripts/BananaController.cs
Labels: enhancement

#201 200 try to implement minimap mechanic
  IoTether/Assets/MinimapRenderTexture.asset
  IoTether/Assets/MinimapRenderTexture.asset.meta
  IoTether/Assets/Prefabs/Canvas (UI).prefab
  IoTether/Assets/Prefabs/Enemies/Evil Mage.prefab
  IoTether/Assets/Prefabs/Enemies/Evil Wizard.prefab
  IoTether/Assets/Prefabs/Enemies/Gremlin.prefab
  IoTether/Assets/Prefabs/Enemies/Small Devil.prefab
  IoTether/Assets/Prefabs/Enemies/SmallSkeleton.prefab
  IoTether/Assets/Prefabs/Enemies/Snail.prefab
  IoTether/Assets/Prefabs/Main Camera.prefab
  IoTether/Assets/Prefabs/Main Camera.prefab.meta
  IoTether/Assets/Prefabs/Managers/AudioManager.prefab
  IoTether/Assets/Prefabs/PlayerParent.prefab
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scenes/Level1.unity
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scenes/Level3.unity
  IoTether/Assets/Scenes/Level4.unity
  IoTether/Assets/Scenes/Level5.unity
  IoTether/ProjectSettings/TagManager.asset
Labels: enhancement

#203 202 implement walls into minimap
  IoTether/Assets/Art/Tileset/square-100.png
  IoTether/Assets/Art/Tileset/square-100.png.meta
  IoTether/Assets/Prefabs/Banana.prefab
  IoTether/Assets/Prefabs/Enemies/SmallSkeleton.prefab
  IoTether/Assets/Prefabs/Minimap.meta
  IoTether/Assets/Prefabs/Minimap/MiniMapGenerator.prefab
  IoTether/Assets/Prefabs/Minimap/MiniMapGenerator.prefab.meta
  IoTether/Assets/Prefabs/NPC.prefab
  IoTether/Assets/Prefabs/Perks/BasePerk.prefab
  IoTether/Assets/Prefabs/Props/Chest.prefab
  IoTether/Assets/Prefabs/Props/Energy Fountain.prefab
  IoTether/Assets/Prefabs/Props/Health Fountain.prefab
  IoTether/Assets/Prefabs/Props/PerkChest.prefab
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scenes/Level1.unity
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scenes/Level3.unity
  IoTether/Assets/Scenes/Level4.unity
  IoTether/Assets/Scenes/Level5.unity
  IoTether/Assets/Scenes/TutorialScene.unity
  IoTether/Assets/Scripts/UIScripts/MinimapTPGenerator.cs
  IoTether/Assets/Scripts/UIScripts/MinimapTPGenerator.cs.meta
  IoTether/Assets/Tiles/TilemapSquare.prefab
  IoTether/Assets/Tiles/TilemapSquare.prefab.meta
  IoTether/Assets/Tiles/square-100.asset
  IoTether/Assets/Tiles/square-100.asset.meta
Labels: enhancement

#206 205 add last few changes for ms3
  IoTether/Assets/Animation/EnergyFountain.meta
  IoTether/Assets/Animation/EnergyFountain/Bottom.anim
  IoTether/Assets/Animation/EnergyFountain/Bottom.anim.meta
  IoTether/Assets/Animation/EnergyFountain/Bottom.controller
  IoTether/Assets/Animation/EnergyFountain/Bottom.controller.meta
  IoTether/Assets/Animation/EnergyFountain/Top.anim
  IoTether/Assets/Animation/EnergyFountain/Top.anim.meta
  IoTether/Assets/Animation/EnergyFountain/Top.controller
  IoTether/Assets/Animation/EnergyFountain/Top.controller.meta
  IoTether/Assets/Animation/HealthFountain.meta
  IoTether/Assets/Animation/HealthFountain/Bottom.controller
  IoTether/Assets/Animation/HealthFountain/Bottom.controller.meta
  IoTether/Assets/Animation/HealthFountain/BottomIdle.anim
  IoTether/Assets/Animation/HealthFountain/BottomIdle.anim.meta
  IoTether/Assets/Animation/HealthFountain/Idle.anim
  IoTether/Assets/Animation/HealthFountain/Idle.anim.meta
  IoTether/Assets/Animation/HealthFountain/Top 1.controller
  IoTether/Assets/Animation/HealthFountain/Top 1.controller.meta
  IoTether/Assets/Animation/HealthFountain/TopIdle.anim
  IoTether/Assets/Animation/HealthFountain/TopIdle.anim.meta
  IoTether/Assets/Prefabs/Banana.prefab
  IoTether/Assets/Prefabs/Main Camera.prefab
  IoTether/Assets/Prefabs/NPC.prefab
  IoTether/Assets/Prefabs/Perks/BasePerk.prefab
  IoTether/Assets/Prefabs/Perks/Energy/MassiveEnergyPerk Variant.prefab
  IoTether/Assets/Prefabs/Perks/Energy/MassiveEnergyPerk Variant.prefab.meta
  IoTether/Assets/Prefabs/Perks/Health/MassiveHealthPerk Variant.prefab
  IoTether/Assets/Prefabs/Perks/Health/MassiveHealthPerk Variant.prefab.meta
  IoTether/Assets/Prefabs/Perks/Speed/MassiveSpeedPerk Variant.prefab
  IoTether/Assets/Prefabs/Perks/Speed/MassiveSpeedPerk Variant.prefab.meta
  IoTether/Assets/Prefabs/PlayerParent.prefab
  IoTether/Assets/Prefabs/Props/Chest.prefab
  IoTether/Assets/Prefabs/Props/Energy Fountain.prefab
  IoTether/Assets/Prefabs/Props/Health Fountain.prefab
  IoTether/Assets/Prefabs/Props/PerkChest.prefab
  IoTether/Assets/Prefabs/Weapons/Equipped Weapons/Sword.prefab
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scenes/Level1.unity
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scenes/Level4.unity
  IoTether/Assets/Scenes/Level6.unity
  IoTether/Assets/Scripts/EnemyScripts/EnergyPickup.cs
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/MassiveEnergyPerk.asset
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/MassiveEnergyPerk.asset.meta
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/MassiveHealthPerk.asset
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/MassiveHealthPerk.asset.meta
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/MassiveSpeedPerk.asset
  IoTether/Assets/Scripts/PerkScripts/Perk Objects/MassiveSpeedPerk.asset.meta
  IoTether/Assets/Scripts/WeaponScripts/Bullet Controllers/BulletController.cs
  IoTether/ProjectSettings/TagManager.asset
Labels: enhancement

#212 Add Confirmation Screen to PauseMenuController and Change Volume of r…
  IoTether/Assets/Prefabs/Canvas (UI).prefab
  IoTether/Assets/Prefabs/Props/Energy Fountain.prefab
  IoTether/Assets/Prefabs/Props/Health Fountain.prefab
  IoTether/Assets/Prefabs/Weapons/Equipped Weapons/Burst Rifle.prefab
  IoTether/Assets/Prefabs/Weapons/Equipped Weapons/Rifle.prefab
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scripts/Managers/UIManager.cs
  IoTether/Assets/Scripts/UIScripts/PauseMenuController.cs
Labels: enhancement

#214 Redesign weapons bench
  IoTether/Assets/Animation/Enemies/TreeStriker.controller
  IoTether/Assets/Scenes/Level6.unity
Labels: bug, high priority

#216 Fix Fade Text Bug with Dialogue Trigger
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scripts/Managers/UIManager.cs
Labels: bug, enhancement
