Repository bmanara/IoTether, pull requests merged in 2024-06, with the labels that each got.

#95 Add FinalDoor Prefab and Edit Scenes
  IoTether/Assets/Prefabs/FinalDoor.prefab
  IoTether/Assets/Prefabs/FinalDoor.prefab.meta
  IoTether/Assets/Scenes/Level1.unity
  IoTether/Assets/Scenes/TutorialScene.unity
  IoTether/Assets/Scripts/StageScripts/DoorManager.cs
  IoTether/Assets/Scripts/StageScripts/FinalDoorManager.cs
  IoTether/Assets/Scripts/StageScripts/FinalDoorManager.cs.meta
Labels: enhancement

#98 97 finish stage 2 design
  IoTether/Assets/Impact Effect Assets/Hit Impact Effects/Pipeline Upgrade/Hit Impacts Effects FREE - URP.unitypackage.meta
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scripts/WeaponScripts/BulletController.cs
Labels: enhancement

#102 99 add room 4 to stage 2
  IoTether/Assets/Impact Effect Assets/Hit Impact Effects/Pipeline Upgrade/Hit Impacts Effects FREE - URP.unitypackage.meta
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scripts/StageScripts/SpikeMovement.cs
Labels: enhancement

#104 103 create boss level
  IoTether/Assets/BRoom Wall Brush.asset
  IoTether/Assets/BRoom Wall Brush.asset.meta
  IoTether/Assets/Prefabs/Props/Boss Room Wall (Left).prefab
  IoTether/Assets/Prefabs/Props/Boss Room Wall (Left).prefab.meta
  IoTether/Assets/Scenes/Level3.unity
  IoTether/Assets/Scenes/Level3.unity.meta
  IoTether/Assets/Scripts/BossRoom Scripts.meta
  IoTether/Assets/Scripts/BossRoom Scripts/BossManager.cs
  IoTether/Assets/Scripts/BossRoom Scripts/BossManager.cs.meta
  IoTether/Assets/Scripts/BossRoom Scripts/BossTrigger.cs
  IoTether/Assets/Scripts/BossRoom Scripts/BossTrigger.cs.meta
  IoTether/Assets/Scripts/Managers/ScenesManager.cs
  IoTether/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#107 101 fix bug regarding main menu
  IoTether/Assets/Impact Effect Assets/Hit Impact Effects/Pipeline Upgrade/Hit Impacts Effects FREE - URP.unitypackage.meta
  IoTether/Assets/Scenes/StartMenuScene.unity
  IoTether/Assets/Scripts/Managers/GameManager.cs
  IoTether/Assets/Scripts/Managers/UIManager.cs
  IoTether/Assets/Scripts/PlayerScripts/PlayerControllers.cs
  IoTether/Assets/Scripts/PlayerScripts/PlayerHealth.cs
  IoTether/Assets/Scripts/UIScripts/GameOverController.cs
  IoTether/Assets/Scripts/UIScripts/MainMenuController.cs
  IoTether/Assets/Scripts/WeaponScripts/WeaponSwap.cs
Labels: bug

#108 31 add pause menu into game
  IoTether/Assets/Prefabs/Canvas (UI).prefab
  IoTether/Assets/Scripts/DialogueTrigger.cs
  IoTether/Assets/Scripts/Managers/GameManager.cs
  IoTether/Assets/Scripts/Managers/UIManager.cs
  IoTether/Assets/Scripts/PlayerScripts/PlayerControllers.cs
  IoTether/Assets/Scripts/UIScripts/PauseMenuController.cs
  IoTether/Assets/Scripts/WeaponScripts/AimController.cs
  IoTether/Assets/Scripts/WeaponScripts/RangedWeapon.cs
  IoTether/Assets/Scripts/WeaponScripts/RifleController.cs
Labels: bug, enhancement

#114 105 add text overlay to display stage and room
  IoTether/Assets/Animation/AC_Text.controller
  IoTether/Assets/Animation/AC_Text.controller.meta
  IoTether/Assets/Animation/Fading Prompt.anim
  IoTether/Assets/Animation/Fading Prompt.anim.meta
  IoTether/Assets/FadeAwayScript.cs
  IoTether/Assets/FadeAwayScript.cs.meta
  IoTether/Assets/Prefabs/Canvas (UI).prefab
  IoTether/Assets/Prefabs/Text.meta
  IoTether/Assets/Prefabs/Text/Room Enter Text.meta
  IoTether/Assets/Prefabs/Text/Room Enter Text/Room 1.prefab
  IoTether/Assets/Prefabs/Text/Room Enter Text/Room 1.prefab.meta
  IoTether/Assets/Prefabs/Text/Room Enter Text/Room Trigger.prefab
  IoTether/Assets/Prefabs/Text/Room Enter Text/Room Trigger.prefab.meta
  IoTether/Assets/RoomEntryTextScript.cs
  IoTether/Assets/RoomEntryTextScript.cs.meta
  IoTether/Assets/RoomTriggerScript.cs
  IoTether/Assets/RoomTriggerScript.cs.meta
  IoTether/Assets/Scenes/Level1.unity
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scenes/Level3.unity
  IoTether/Assets/Scenes/TutorialScene.unity
  IoTether/Assets/Scripts/Managers/UIManager.cs
  IoTether/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: enhancement

#116 Rework GameManager to add slight delay before respawning player
  IoTether/Assets/RoomTriggerScript.cs
  IoTether/Assets/RoomTriggerScript.cs.meta
  IoTether/Assets/Scripts/Managers/GameManager.cs
  IoTether/Assets/Scripts/StageScripts/RoomEntryTextScript.cs
  IoTether/Assets/Scripts/StageScripts/RoomEntryTextScript.cs.meta
Labels: bug

#120 119 change npc icons and animation
  IoTether/Assets/Animation/Enemies.meta
  IoTether/Assets/Animation/Enemies/Small Devil.controller
  IoTether/Assets/Animation/Enemies/Small Devil.controller.meta
  IoTether/Assets/Animation/Enemies/SmallDevilAttack.anim
  IoTether/Assets/Animation/Enemies/SmallDevilAttack.anim.meta
  IoTether/Assets/Animation/Enemies/SmallDevilIdle.anim
  IoTether/Assets/Animation/Enemies/SmallDevilIdle.anim.meta
  IoTether/Assets/Animation/Enemies/SmallDevilWalk.anim
  IoTether/Assets/Animation/Enemies/SmallDevilWalk.anim.meta
  IoTether/Assets/Animation/Enemies/SmallSkeleton.controller
  IoTether/Assets/Animation/Enemies/SmallSkeleton.controller.meta
  IoTether/Assets/Animation/Enemies/SmallSkeletonIdle.anim
  IoTether/Assets/Animation/Enemies/SmallSkeletonIdle.anim.meta
  IoTether/Assets/Animation/Enemies/SmallSkeletonWalk.anim
  IoTether/Assets/Animation/Enemies/SmallSkeletonWalk.anim.meta
  IoTether/Assets/Animation/NPC's.meta
  IoTether/Assets/Animation/NPC's/BeardedController.controller
  IoTether/Assets/Animation/NPC's/BeardedController.controller.meta
  IoTether/Assets/Animation/NPC's/BeardedIdle.anim
  IoTether/Assets/Animation/NPC's/BeardedIdle.anim.meta
  IoTether/Assets/Animation/NPC's/KnightController.controller
  IoTether/Assets/Animation/NPC's/KnightController.controller.meta
  IoTether/Assets/Animation/NPC's/KnightIdle.anim
  IoTether/Assets/Animation/NPC's/KnightIdle.anim.meta
  IoTether/Assets/Animation/NPC's/TutorialMaster.controller
  IoTether/Assets/Animation/NPC's/TutorialMaster.controller.meta
  IoTether/Assets/Animation/NPC's/TutorialMasterIdle.anim
  IoTether/Assets/Animation/NPC's/TutorialMasterIdle.anim.meta
  IoTether/Assets/Animation/Player.meta
  IoTether/Assets/Animation/Player/Player.controller
  IoTether/Assets/Animation/Player/Player.controller.meta
  IoTether/Assets/Animation/Player/PlayerIdle.anim
  IoTether/Assets/Animation/Player/PlayerIdle.anim.meta
  IoTether/Assets/Animation/Player/PlayerWalk.anim
  IoTether/Assets/Animation/Player/PlayerWalk.anim.meta
  IoTether/Assets/Animation/Text.meta
  IoTether/Assets/Animation/Text/DialogueBox.controller
  IoTether/Assets/Animation/Text/DialogueBox.controller.meta
  IoTether/Assets/Animation/Text/DialogueBoxClose.anim
  IoTether/Assets/Animation/Text/DialogueBoxClose.anim.meta
  IoTether/Assets/Animation/Text/DialogueBoxOpen.anim
  IoTether/Assets/Animation/Text/DialogueBoxOpen.anim.meta
  IoTether/Assets/Animation/Text/Fading Prompt.anim
  IoTether/Assets/Animation/Text/Fading Prompt.anim.meta
  IoTether/Assets/Impact Effect Assets/Hit Impact Effects/Pipeline Upgrade/Hit Impacts Effects FREE - URP.unitypackage.meta
  IoTether/Assets/Prefabs/Text/Room Enter Text/Room Trigger.prefab
  IoTether/Assets/Scenes/Level1.unity
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scenes/Level3.unity
Labels: enhancement

#123 78 improve room transition
  IoTether/Assets/AstarPathfindingProject/Core/AstarPath.cs
  IoTether/Assets/Impact Effect Assets/Hit Impact Effects/Pipeline Upgrade/Hit Impacts Effects FREE - URP.unitypackage.meta
  IoTether/Assets/Prefabs/Canvas (UI).prefab
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scenes/Level3.unity
  IoTether/Assets/Scenes/TutorialScene.unity
  IoTether/Assets/Scripts/Managers/GameManager.cs
  IoTether/Assets/Scripts/Managers/UIManager.cs
  IoTether/Assets/Scripts/TextScripts.meta
  IoTether/Assets/Scripts/TextScripts/Dialogue.cs
  IoTether/Assets/Scripts/TextScripts/Dialogue.cs.meta
  IoTether/Assets/Scripts/TextScripts/DialogueTrigger.cs
  IoTether/Assets/Scripts/TextScripts/DialogueTrigger.cs.meta
  IoTether/Assets/Scripts/TextScripts/FadeAwayScript.cs
  IoTether/Assets/Scripts/TextScripts/FadeAwayScript.cs.meta
  IoTether/Assets/Scripts/TextScripts/LoadingTextScript.cs
  IoTether/Assets/Scripts/TextScripts/LoadingTextScript.cs.meta
  IoTether/Assets/Scripts/WeaponScripts/PistolController.cs
Labels: enhancement

#125 124 add room clear text to adaptive text
  IoTether/Assets/Prefabs/Canvas (UI).prefab
  IoTether/Assets/Scenes/Level1.unity
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scenes/TutorialScene.unity
  IoTether/Assets/Scripts/EnemyScripts/MeleeAstarAI.cs
  IoTether/Assets/Scripts/Managers/UIManager.cs
  IoTether/Assets/Scripts/StageScripts/DoorManager.cs
  IoTether/Assets/Scripts/StageScripts/FinalDoorManager.cs
  IoTether/Assets/Scripts/StageScripts/RoomEntryTextScript.cs
Labels: enhancement

#130 127 implement perk skeleton
  IoTether/Assets/Impact Effect Assets/Hit Impact Effects/Pipeline Upgrade/Hit Impacts Effects FREE - URP.unitypackage.meta
  IoTether/Assets/Prefabs/Canvas (UI).prefab
  IoTether/Assets/Prefabs/Perks.meta
  IoTether/Assets/Prefabs/Perks/BasePerk.prefab
  IoTether/Assets/Prefabs/Perks/BasePerk.prefab.meta
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scripts/PerkScripts.meta
  IoTether/Assets/Scripts/PerkScripts/BigHealthPerk.asset
  IoTether/Assets/Scripts/PerkScripts/BigHealthPerk.asset.meta
  IoTether/Assets/Scripts/PerkScripts/EnergyPerk.cs
  IoTether/Assets/Scripts/PerkScripts/EnergyPerk.cs.meta
  IoTether/Assets/Scripts/PerkScripts/HealthPerk.cs
  IoTether/Assets/Scripts/PerkScripts/HealthPerk.cs.meta
  IoTether/Assets/Scripts/PerkScripts/IPerk.cs
  IoTether/Assets/Scripts/PerkScripts/IPerk.cs.meta
  IoTether/Assets/Scripts/PerkScripts/Powerup.cs
  IoTether/Assets/Scripts/PerkScripts/Powerup.cs.meta
  IoTether/Assets/Scripts/PerkScripts/SmallEnergyPerk.asset
  IoTether/Assets/Scripts/PerkScripts/SmallEnergyPerk.asset.meta
  IoTether/Assets/Scripts/PerkScripts/SmallHealthPerk.asset
  IoTether/Assets/Scripts/PerkScripts/SmallHealthPerk.asset.meta
  IoTether/Assets/Scripts/PlayerScripts/PlayerHealth.cs
Labels: enhancement

#133 132 enable adaptive text for perk
  IoTether/Assets/Impact Effect Assets/Hit Impact Effects/Pipeline Upgrade/Hit Impacts Effects FREE - URP.unitypackage.meta
  IoTether/Assets/Prefabs/Canvas (UI).prefab
  IoTether/Assets/Prefabs/Perks/BasePerk.prefab
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scripts/Managers/UIManager.cs
  IoTether/Assets/Scripts/PerkScripts/Powerup.cs
Labels: enhancement

#136 Improve TutorialScene
  IoTether/Assets/Prefabs/Canvas (UI).prefab
  IoTether/Assets/Prefabs/Props/Door.prefab
  IoTether/Assets/Prefabs/Text/Room Enter Text/Text Trigger.prefab
  IoTether/Assets/Prefabs/Text/Room Enter Text/Text Trigger.prefab.meta
  IoTether/Assets/Scenes/TutorialScene.unity
  IoTether/Assets/Scripts/Managers/UIManager.cs
  IoTether/Assets/Scripts/StageScripts/DoorManager.cs
  IoTether/Assets/Scripts/StageScripts/FinalDoorManager.cs
  IoTether/Assets/Scripts/StageScripts/RoomEntryTextScript.cs
Labels: enhancement

#145 144 create perk box
  IoTether/Assets/Prefabs/Perks/EnergyPerk Variant.prefab
  IoTether/Assets/Prefabs/Perks/EnergyPerk Variant.prefab.meta
  IoTether/Assets/Prefabs/Perks/HealthPerk Variant.prefab
  IoTether/Assets/Prefabs/Perks/HealthPerk Variant.prefab.meta
  IoTether/Assets/Prefabs/Perks/PerkCanvas.meta
  IoTether/Assets/Prefabs/Perks/PerkCanvas/PerkButton.prefab
  IoTether/Assets/Prefabs/Perks/PerkCanvas/PerkButton.prefab.meta
  IoTether/Assets/Prefabs/Perks/PerkCanvas/PerkCanvas.prefab
  IoTether/Assets/Prefabs/Perks/PerkCanvas/PerkCanvas.prefab.meta
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scenes/Level2.unity
  IoTether/Assets/Scenes/Level3.unity
  IoTether/Assets/Scripts/Managers/GameManager.cs
  IoTether/Assets/Scripts/Managers/UIManager.cs
  IoTether/Assets/Scripts/PerkScripts/EnergyPerk.cs
  IoTether/Assets/Scripts/PerkScripts/HealthPerk.cs
  IoTether/Assets/Scripts/PerkScripts/Perk Panel.meta
  IoTether/Assets/Scripts/PerkScripts/Perk Panel/PerkSelectManager.cs
  IoTether/Assets/Scripts/PerkScripts/Perk Panel/PerkSelectManager.cs.meta
  IoTether/Assets/Scripts/PerkScripts/PerkButton.cs
  IoTether/Assets/Scripts/PerkScripts/PerkButton.cs.meta
  IoTether/Assets/Scripts/PerkScripts/QuirkButton.cs
  IoTether/Assets/Scripts/PerkScripts/QuirkButton.cs.meta
  IoTether/Assets/Scripts/PerkScripts/SmallHealthPerk.asset
  IoTether/Assets/Scripts/PlayerScripts/PlayerEnergy.cs
  IoTether/Assets/Scripts/PlayerScripts/PlayerHealth.cs
  IoTether/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: enhancement

#154 Add extended DialogueTrigger for Perk NPC
  IoTether/Assets/Prefabs/Perk NPC Variant.prefab
  IoTether/Assets/Prefabs/Perk NPC Variant.prefab.meta
  IoTether/Assets/Scenes/HughScene.unity
  IoTether/Assets/Scenes/Level3.unity
  IoTether/Assets/Scripts/TextScripts/DialogueTrigger.cs
  IoTether/Assets/Scripts/TextScripts/PerkDialogueTrigger.cs
  IoTether/Assets/Scripts/TextScripts/PerkDialogueTrigger.cs.meta
Labels: enhancement
